#!/bin/bash
#
# Tit Petric (tit.petric@monotek.net) / Tue 07 May 2013 01:35:01 PM CEST
#

function git_status_folder
{
	dir=${1}
	cd ${dir}

	OIFS=${IFS}
	NIFS=$'\n'

	IFS=${NIFS}

	GITSTATUS=`git status | grep 'is ahead' ; git status --porcelain`
	if [ -n "$GITSTATUS" ]; then
		echo -e "\e[93m# ${dir}\e[0m"
		for CHANGE in $GITSTATUS
		do
			IFS=${OIFS}
			echo $CHANGE
			IFS=${NIFS}
		done
	fi

	IFS=$OIFS
	cd ${ORIGPWD}
}

ORIGPWD=${PWD}
REPOS=`find -type d -name '.git' | sed 's/\/\.git//g'`
for REPO in $REPOS
do
	if [ "$REPO" == "." ]; then
		continue;
	fi
	git_status_folder "$REPO"
done

GITDIR=`git rev-parse --git-dir 2>&1`
if [ $? -eq 0 ]; then
	REPOPATH=`echo $GITDIR | sed 's/\/\?\.git$//'`
	if [ -z "$REPOPATH" ]; then
		REPOPATH=$ORIGPWD;
	fi
	git_status_folder "$REPOPATH";
fi
