#!/bin/bash
#
# Tit Petric (tit.petric@monotek.net) / Tue 07 May 2013 01:35:01 PM CEST
#

function git_status_folder
{
	dir=${1}
	cd ${dir}
	echo \# ${dir}
	git status --porcelain
	cd ${ORIGPWD}
}

ORIGPWD=${PWD}
REPOS=`find -type d -name '.git' | sed 's/\/\.git//g'`
for REPO in $REPOS
do
	if [ "$REPO" == "." ]; then
		continue;
	fi
	git_status_folder "$REPO"
done

GITDIR=`git rev-parse --git-dir 2>&1`
if [ $? -eq 0 ]; then
	REPOPATH=`echo $GITDIR | sed 's/\/\?\.git//'`
	if [ -z "$REPOPATH" ]; then
		REPOPATH=$ORIGPWD;
	fi
	git_status_folder "$REPOPATH";
fi
